//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPosition
    {
        public Nullable<long> IdPosition { get; set; }
        public long IdAccess { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual Position Position { get; set; }
    }
}
