//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Access()
        {
            this.AccessRequesteds = new HashSet<AccessRequested>();
        }
    
        public long ID { get; set; }
        public string Access1 { get; set; }
        public long IdApplication { get; set; }
        public string Level { get; set; }
        public long IdApprover { get; set; }
    
        public virtual AccessPosition AccessPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessRequested> AccessRequesteds { get; set; }
        public virtual Application Application { get; set; }
        public virtual Approver Approver { get; set; }
    }
}
