//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessRequested
    {
        public long IdRequest { get; set; }
        public long IdAccess { get; set; }
        public long IdStatus { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual Request Request { get; set; }
        public virtual Status Status { get; set; }
    }
}
