//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.AccessRequesteds = new HashSet<AccessRequested>();
        }
    
        public long ID { get; set; }
        public Nullable<long> IdEmployee { get; set; }
        public Nullable<long> IdPosition { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<long> IdSupervisor { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessRequested> AccessRequesteds { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
